### ISSUE TITLE
New Icons

### ISSUE THREAD

**Issue by decknine** [XBMC-Addons/resource.images.studios.white#20]
I couldn't figure out how to merge/submit whatever new icons for approval. Here you go should you want them.
[studios EXTRA.zip](https://github.com/XBMC-Addons/resource.images.studios.white/files/2437126/studios.EXTRA.zip)

**Comment by AMoo-Miki** [comment]
Thanks. I will take care of it.

**Comment by AMoo-Miki** [comment]
@ronie, I am still working on these; they are over 1,300 images and all are named in lowercase.

1) Many seem to be music studios; is that a problem?
2) Do you know of any skins/scrappers that use Studio icons for music videos or musics? This will help me find the correct names.

**Comment by ronie** [comment]
for music we have a RecordLabels addon:
https://github.com/XBMC-Addons/resource.images.recordlabels.white

i don't think skins are using Studios for music.

**Comment by AMoo-Miki** [comment]
Then I will start selectively pushing images from this catalog in here or there.

@decknine, did you use these on specific movies or shows that you feel should be included in this plugin specifically? Am I wrong in believing many are music studios?

**Comment by ronie** [comment]
yes, that zip file contains mainly icons that are included in the RecordLabels addon.
That should not be added in this Studios addon.

**Comment by AMoo-Miki** [comment]
Cool. Thanks for confirming. I will compare and contrast.
