### ISSUE TITLE
Updated and New Logos

### ISSUE THREAD

**Issue by aussiehuddo** [XBMC-Addons/resource.images.studios.white#21]
[New Logos.zip](https://github.com/XBMC-Addons/resource.images.studios.white/files/2996226/New.Logos.zip)

I have made these new and updated logos for a number of TV and movie studios.

Happy to make other logos if needed.

Cheers

**Comment by ronie** [comment]
thanx for sharing these!

i've added them to the addon: https://github.com/XBMC-Addons/resource.images.studios.white/commit/2af28c7eee7cbf592040a6bc938b7876dc3a084f
