### ISSUE TITLE
Few issues from last update

### ISSUE THREAD

**Issue by aussiehuddo** [XBMC-Addons/resource.images.studios.white#22]
Just a sub update from the previous one.

I uploaded the following logos last time as updates but the old one is still there, could you please replace them:
- Blumhouse Productions
- LifeStyle
- Lucasfilm
- NickToons
- Pixar
- Playboy TV

I have updated the "E4" logo to have a grey area to make it more obvious.

Last time I uploaded "TVNZ1" and "TVNZ2", these were trial files and can be deleted and replaced with the "TVNZ" file in this upload.

I have also added "Comedy Channel" and "The Comedy Channel (AU)" as new logos.

A couple of other questions I have:
- Is there a plan to have higher res files in the future?
- How long does it take for the updates to this resource to show in Kodi?

Cheers

[New Logos 28.03.2019.zip](https://github.com/XBMC-Addons/resource.images.studios.white/files/3016199/New.Logos.28.03.2019.zip)

**Comment by ronie** [comment]
thx, added: https://github.com/XBMC-Addons/resource.images.studios.white/commit/087343db3cd03ec167f688cbdfc16af43fcae9a8

1) as far as i know no one is working on an addon for hi-res studio logos

2) the changes made in this repo will have to be submitted to the kodi addon repo.
i usually do this when a fair amount of icons have been added/updated.
will do that later today.
