### ISSUE TITLE
TV Channels' logo

### ISSUE THREAD

**Issue by helviojr** [XBMC-Addons/resource.images.studios.white#38]
This is more a question/doubt than actually a issue to be solved.

I know TV channels' logos are to be downloaded by the user him/herself or automatically using the url in m3u file, but many TV channels' logo already exists in resource.images.studio.white. Mostly because those channels produces movies and TV series, but there are logos that are only to satisfy different channels from the same TV company.

For example, there are logos for what is clearly TV channels, like Eurosport, Eurosport 1, Eurosport3, France 2, France 2 Cinema, France 3, France 3 Cinema, Fox HD, Fox 8, FX HD, many xxx-HD etc.

The question is: is it OK for me to send other icons that are channel logos rather than actually the name of a movie producer studio? For example, we have, in Brazil, the SporTV channels. They produce many videos (specially documentaries on sports), so their logo belongs here. But they have simultaneous live TV feeds in 3 channels, so 3 logos (SporTV, SporTV 2, SporTV 3). Should I create all 3 logos?

**Comment by ronie** [comment]
sure, channel logos are more than welcome.
