### ISSUE TITLE
add movie studio icons

### ISSUE THREAD

**Issue by Konon-cat** [XBMC-Addons/resource.images.studios.white#44]
[Gorky Film Studio](https://en.wikipedia.org/wiki/Gorky_Film_Studio), [Dovzhenko Film Studio](https://en.wikipedia.org/wiki/Dovzhenko_Film_Studios), [Lenfilm](https://en.wikipedia.org/wiki/Lenfilm), [Odessa Film Studio](https://en.wikipedia.org/wiki/Odessa_Film_Studio)

[images studios white.zip](https://github.com/XBMC-Addons/resource.images.studios.white/files/5411718/images.studios.white.zip)

**Comment by ronie** [comment]
added, thx!
https://github.com/XBMC-Addons/resource.images.studios.white/commit/db9e9c47817551e044cb6a6f0a46a8d556ac3147
