### ISSUE TITLE
TV and Movie Studios icons

### ISSUE THREAD

**Issue by Roney-b** [XBMC-Addons/resource.images.studios.white#49]
There are some missing studios and TV channel icons.

[Icons.zip](https://github.com/XBMC-Addons/resource.images.studios.white/files/6251274/Icons.zip)

**Comment by ronie** [comment]
thx, i've added them.
much appreciated!

https://github.com/XBMC-Addons/resource.images.studios.white/commit/0bbb94615a31c263d50dced17b4c321e9dd3c885
