### ISSUE TITLE
add movie studio icon

### ISSUE THREAD

**Issue by Konon-cat** [XBMC-Addons/resource.images.studios.white#54]
[Sverdlovsk Film Studio](https://en.wikipedia.org/wiki/Sverdlovsk_Film_Studio)
[Sverdlovskfilm.zip](https://github.com/XBMC-Addons/resource.images.studios.white/files/7588333/Sverdlovskfilm.zip)

**Comment by ronie** [comment]
thx, the logo has been added:
https://github.com/XBMC-Addons/resource.images.studios.white/commit/46762ac34c89b5b19a3d814dd6368057018a7024
