### ISSUE TITLE
More Studios

### ISSUE THREAD

**Issue by annomatik** [XBMC-Addons/resource.images.studios.white#57]
Here's another set of white studio icons... So, if the repository has been updated, will these show up in my Kodi automatically?

Thanks!

[icons1.zip](https://github.com/XBMC-Addons/resource.images.studios.white/files/8319691/icons1.zip)

**Comment by ronie** [comment]
thanx again, they have been added:
https://github.com/XBMC-Addons/resource.images.studios.white/commit/6f43b321ec37907b867df4869b0775c077c72e49

the addon in Kodi will be updated once an update has been submitted to the kodi addon repository.
i'll take care of that as well.

**Comment by annomatik** [comment]
Thank you!
