### ISSUE TITLE
Icons don't update

### ISSUE THREAD

**Issue by annomatik** [XBMC-Addons/resource.images.studios.white#58]
Hi! No rush, just a question... When I look into the official (?) Kodi repository, the latest version of the icon pack there seems to be 0.28. But the current icon pack version is 0.30, right?

https://mirrors.kodi.tv/addons/leia/resource.images.studios.white/

I tried adding the icons manually, by using the kodi texture tool to pack the new stuff into Textures.xbt, the result was, that no icon at all showed up :-) (just putting the PNGS into the resources-folder of course doesn't work either).

So my questions are...
1) can you estimate, how long it takes the kodi-addons repository to update?
2) is there a place where I can download a current zip file in a way, that I can import manually in Kodi?

Thanks!

**Comment by ronie** [comment]
there was a small issue getting the update in the kodi addon repo,
but it has been merged now: https://github.com/xbmc/repo-resources/pull/231

you should receive the updated version in kodi within the next 24 hours
