### ISSUE TITLE
studio icons

### ISSUE THREAD

**Issue by Tee77** [XBMC-Addons/resource.images.studios.white#60]
[studio icons.zip](https://github.com/XBMC-Addons/resource.images.studios.white/files/8693744/studio.icons.zip)

City Light Films, Baby Cow Productions

Thanks

**Comment by ronie** [comment]
added, thx!
https://github.com/XBMC-Addons/resource.images.studios.white/commit/660dda18538974dc226e3411d9d8218ad929eb50
